### ISSUE TITLE
/task/<id>/user_task

### ISSUE THREAD

**Issue by teymour-aldridge** [MLH-Fellowship/0.5.1-household#23]
Inputs: none
Returns: `{"data": [{"user_id": <user id>, "deadline": <integer – UNIX timestamp in UTC timezone>, "house_id": <house id>]}`

**Comment by gmelodie** [comment]
@teymour-aldridge there's no `house_id` on the UserTask model, should we add it?

**Comment by teymour-aldridge** [comment]
I think it should be possible to achieve this by querying through `Task` which has a `house_id` field. You might need to set up a `db.relationship`

**Comment by teymour-aldridge** [comment]
https://flask-sqlalchemy.palletsprojects.com/en/2.x/models/#one-to-many-relationships

**Comment by teymour-aldridge** [comment]
https://docs.sqlalchemy.org/en/13/orm/relationship_api.html#sqlalchemy.orm.relationship

**Comment by gmelodie** [comment]
> I think it should be possible to achieve this by querying through `Task` which has a `house_id` field. You might need to set up a `db.relationship`

Yeah I think that's a model issue then #24. Will block this until model is updated
