### ISSUE TITLE
Create database models.

### ISSUE THREAD

**Issue by teymour-aldridge** [MLH-Fellowship/0.5.1-household#7]
We're probably using SQLAlchemy with Postgres.
The schema should look something like:
**House**
~– Join code~ _(use invite links instead)_
– Name
– Description
**UserHouse**
– User ID
– House ID
**Task**
– Name
– Description
– House ID
– Frequency
**UserTask**
– Task ID
– User ID
– Deadline
– In progress?
– Is done?

**Comment by gmelodie** [comment]
Base models added on #11
