### ISSUE TITLE
API schema

### ISSUE THREAD

**Issue by teymour-aldridge** [MLH-Fellowship/0.5.1-household#8]
*All routes take JSON objects*
*All routes except for `auth/register` and `auth/login` need a JWT token.*
*The JWT token should be supplied in the `Authorization` header.*
*For any request no data is sent back if a request has status "error"*
e.g. in the headers should look like `Authorization: <some jwt>`
## Auth
**/auth/register**
*Method: POST*
- [x] complete!
- *Inputs:* username [string] + email [string] + password [string]
- *Returns:* `{"data": <user id>, "msg": <some message>, "status": <some status>}`

**/auth/login**
*Method: POST*
- [x] complete!
- *Inputs:* identifier [string, username or email] + password [string]
- *Returns:* JSON object `{"data": <JWT>, "msg": <some message>, "status": <either "error" or "success" – no JWT returned if the status is "error">}`

## House
*Method: POST*
- [x] complete!
**/house/add** 
- *Inputs:* name [string] + description [string]
- *Returns:* `{"data": <user id>, "msg": <some message>, "status": <some status>}`

**`/house/<id>/user/invite`**
*Method: GET*
- [x] complete!
– *Inputs:* none
– *Returns:* JSON object `{"data":  <A generic invite link (anyone can join)>, "msg": <some message>, "status": <either "error" or "success" – no link is returned if the status is "error" – "data" will be blank>}`

**`/house/<id>/get`**
*Method: GET*
- [x] complete!
– *Inputs:* none
– *Returns:* A JSON object `{"data":  {"name": <name>, "description": <description>, "house_id": <house_id>}, "msg": <some message>, "status": <either "error" or "success" – no link is returned if the status is "error" – "data" will be blank>}`

**`/house/<id>/user/invite/<email>`**
*Method: GET*
- [x] complete!
– *Inputs:* none
– *Returns:* A specific invite link (only a user with that invite can join)

**`/house/<id>/user/join?token=<some token>`**
*Method: GET*
- [x] complete!
– *Inputs:* none (note that this link is the one returned from the two endpoints above)
– *Returns:* `{"data": <house id>, "msg": <some message>, "status": <"error" or "success">}`

**/house/update** 
*Method: POST/UPDATE*
- [x] complete!
- *Inputs:* name [optional – string] description [optional – string]
- *Returns:* JSON object `{"data": <house id>, "msg": <some message>, "status": <either "error" or "success">}`
Note that this only updates fields which are provided – i.e. if you send {"name": "new name"} then the description won't be changed

## Task
*Method: POST*
`house/<id>/task/add`
- [x] complete!
– *Inputs:* name [string], description [string], frequency [integer – a number of seconds]
– *Returns* JSON Object `{"data": <task id>, "msg": <some message>, "status": <either "error" or "success">}`

`task/<id>`
*Method: GET*
- [x] complete!
– *Inputs:* none
– *Returns:* JSON Object `{"data": {"name": <task name>, "id": <task id>, "description": <task description>, "frequency": <frequency>}}`

`task/<id>/update`
*Method: POST/UPDATE*
- [x] complete!
– *Inputs:* name [optional – string], description [optional – string], frequency [optional – integer]
– *Returns:* `{"data": <task id>, "msg": <some message>, "status": <either "error" or "success">}`

`/house/<id>/task/all`
*Method: GET*
- [x] complete!
– *Inputs:* none
– *Returns: `{"data": [{"name": <task name>, "id": <task id>, "description": <task description>, "frequency": <frequency>}], "msg": <some message>, "status": <some status>}`

## UserTask
*Method: GET*
`/task/<id>/user_task`
- [x] complete!
– *Inputs:* none
– *Returns:* `{"data": [{"user_id": <user id>, "deadline": <integer – UNIX timestamp in UTC>, "house_id": <house id>]}`

**Comment by gmelodie** [comment]
@teymour-aldridge I'm missing the methods you're thinking about, could you add them?

**Comment by teymour-aldridge** [comment]
Good catch! I'll include them. 😅

**Comment by teymour-aldridge** [comment]
I've added them.

**Comment by gmelodie** [comment]
@teymour-aldridge I've noticed we're slightly out of standard in some endpoints. I suggest always having three fields in the response: `data` (either retrieved data or the id of the data being queried), `msg` (for error messages), and `status` (success or error)

**Comment by teymour-aldridge** [comment]
Yes – sounds good.
